server:
  port: 9120

spring:
  datasource:
    url: jdbc:postgresql://localhost/task-tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
